export const ALL_SKILLS = [
  "Art",
  "Artificial Intelligence",
  "Blockchain",
  "Childcare",
  "Cloud Computing",
  "Cooking",
  "Construction", 
  "Counseling",
  "Customer Service",
  "Cybersecurity",
  "Data Analysis",
  "Data Science",
  "Database Management",
  "DevOps",
  "Education",
  "Event Planning",
  "Financial",
  "First Aid & CPR",
  "Gardening",
  "General Maintenance",
  "Guitar",
  "Handyman",
  "Handwriting",
  "Hiking",
  "Home Repair",
  "Home Staging",
  "Home Security",
  "Home Theater",
  "Home Automation",
  "Home Cleaning",
  "Home Organization",
  "Home Maintenance",
  "Graphic Design",
  "Home Improvement",
  "Insurance",
  "Kanban",
  "Legal",
  "Machine Learning",
  "Manufacturing",
  "Marketing",
  "Medical",
  "Mechanic",
  "Mobile Development",
  "Network Administration",
  "Project Management",
  "Real Estate",
  "Ride Sharing",
  "Sales",
  "Security",
  "Technology",
  "Tech Support",
  "Trading",
  "Crypto",
  "Tutoring",
  "Web Development",
];
